- id: doi:10.1088/1741-2552/ae20c2
  type: paper
  description: This programmable, open-source neurostimulator offers tangible hope for expanding access to non-invasive neuromodulation research and treatments for people with paralysis worldwide.
  date: 2020-12-4
  image: https://content.cld.iop.org/journals/1741-2552/22/6/066021/revision2/jneae20c2f6_lr.jpg
  buttons:
    #- type: manubot
    #  link: https://greenelab.github.io/meta-review/
    #- type: source
    #  text: Manuscript Source
    #  link: https://github.com/greenelab/meta-review
    #- type: website
    #  link: http://manubot.org
  tags:
    - open science
    - collaboration
  repo: OpenMedTech-Lab/OpenXstim

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
